(cl:in-package flexi-msg)
(cl:export '(X-VAL
          X
          X2-VAL
          X2
          X3-VAL
          X3
          X4-VAL
          X4
          X5-VAL
          X5
          X6-VAL
          X6
          X7-VAL
          X7
          X8-VAL
          X8
          X9-VAL
          X9
          X10-VAL
          X10
          X11-VAL
          X11
          X12-VAL
          X12
          X13-VAL
          X13
          X14-VAL
          X14
          X15-VAL
          X15
          X16-VAL
          X16
))